export const MF_PATHS = {
  "./ActivityStatus": "./src/components/atoms/ActivityStatus",
  "./Button": "./src/components/atoms/Button",
  "./ButtonTab": "./src/components/atoms/ButtonTab",
  "./ColorPicker": "./src/components/atoms/ColorPicker",
  "./ConnectorPlain": "./src/components/atoms/ConnectorPlain",
  "./CrawlLine": "./src/components/atoms/CrawlLine",
  "./CriticalityIndicator": "./src/components/atoms/CriticalityIndicator",
  "./DangerRangStatus": "./src/components/atoms/DangerRangStatus",
  "./DateTime": "./src/components/atoms/DateTime",
  "./Deadline": "./src/components/atoms/Deadline",
  "./DeviceStatus": "./src/components/atoms/DeviceStatus",
  "./ForecastStatus": "./src/components/atoms/ForecastStatus",
  "./Icons": "./src/components/atoms/Icons",
  "./IncidentNotificationDeliveryStatus":
    "./src/components/atoms/IncidentNotificationDeliveryStatus",
  "./IncidentNotificationSessionStatus":
    "./src/components/atoms/IncidentNotificationSessionStatus",
  "./IncidentNumberLabel": "./src/components/atoms/IncidentNumberLabel",
  "./IncidentStatus": "./src/components/atoms/IncidentStatus",
  "./IncidentStatusMobile": "./src/components/atoms/IncidentStatusMobile",
  "./InputHeader": "./src/components/atoms/InputHeader",
  "./inputs": "./src/components/atoms/inputs",
  "./JsonViewer": "./src/components/atoms/JsonViewer",
  "./Label": "./src/components/atoms/Label",
  "./Link": "./src/components/atoms/Link",
  "./ListStub": "./src/components/atoms/ListStub",
  "./LocationAdditionalInfo": "./src/components/atoms/LocationAdditionalInfo",
  "./MarkdownView": "./src/components/atoms/MarkdownView",
  "./MenuItem": "./src/components/atoms/MenuItem",
  "./NumericIndicator": "./src/components/atoms/NumericIndicator",
  "./OrderNumberLabel": "./src/components/atoms/OrderNumberLabel",
  "./OrderStatus": "./src/components/atoms/OrderStatus",
  "./ParamBlock": "./src/components/atoms/ParamBlock",
  "./ParamLine": "./src/components/atoms/ParamLine",
  "./ParamLineProperty": "./src/components/atoms/ParamLineProperty",
  "./PointLocation": "./src/components/atoms/PointLocation",
  "./ProgressBar": "./src/components/atoms/ProgressBar",
  "./RelatedincidentLink": "./src/components/atoms/RelatedincidentLink",
  "./selects": "./src/components/atoms/selects",
  "./Separator": "./src/components/atoms/Separator",
  "./SignalNumberLabel": "./src/components/atoms/SignalNumberLabel",
  "./SignalSourceIcon": "./src/components/atoms/SignalSourceIcon",
  "./SignalStatus": "./src/components/atoms/SignalStatus",
  "./Spinner": "./src/components/atoms/Spinner",
  "./StatisticsLegendColor": "./src/components/atoms/StatisticsLegendColor",
  "./Stub": "./src/components/atoms/Stub",
  "./TabItem": "./src/components/atoms/TabItem",
  "./Tag": "./src/components/atoms/Tag",
  "./Text": "./src/components/atoms/Text",
  "./WeatherInfoItem": "./src/components/atoms/WeatherInfoItem",
  "./AudioProgressBar": "./src/components/molecules/AudioProgressBar",
  "./BottomSheet": "./src/components/molecules/BottomSheet",
  "./ButtonTabs": "./src/components/molecules/ButtonTabs",
  "./CardParamLine": "./src/components/molecules/CardParamLine",
  "./CardToggleMenuVisibilityButton":
    "./src/components/molecules/CardToggleMenuVisibilityButton",
  "./CheckboxTreeView": "./src/components/molecules/CheckboxTreeView",
  "./CheckboxTreeViewAdvanced":
    "./src/components/molecules/CheckboxTreeViewAdvanced",
  "./ContactItemLabel": "./src/components/molecules/ContactItemLabel",
  "./DarkModeContainer": "./src/components/molecules/DarkModeContainer",
  "./DatePickerCalendar": "./src/components/molecules/DatePickerCalendar",
  "./DatePickerCalendarHeader":
    "./src/components/molecules/DatePickerCalendarHeader",
  "./DatePickerMonthSelect": "./src/components/molecules/DatePickerMonthSelect",
  "./DatePickerRangeCalendar":
    "./src/components/molecules/DatePickerRangeCalendar",
  "./DatePickerTodayButton": "./src/components/molecules/DatePickerTodayButton",
  "./DndPopupContainer": "./src/components/molecules/DndPopupContainer",
  "./FileList": "./src/components/molecules/FileList",
  "./FileListItem": "./src/components/molecules/FileListItem",
  "./FileUploader": "./src/components/molecules/FileUploader",
  "./GeoButton": "./src/components/molecules/GeoButton",
  "./Header": "./src/components/molecules/Header",
  "./ImageWithSpinner": "./src/components/molecules/ImageWithSpinner",
  "./SearchInput": "./src/components/molecules/Inputs/SearchInput",
  "./layers": "./src/components/molecules/layers",
  "./LineClampContainer": "./src/components/molecules/LineClampContainer",
  "./List": "./src/components/molecules/List",
  "./Menu": "./src/components/molecules/Menu",
  "./Modal": "./src/components/molecules/Modal",
  "./Notify": "./src/components/molecules/Notify",
  "./Notify404": "./src/components/molecules/Notify404",
  "./OptionStepCard": "./src/components/molecules/OptionStepCard",
  "./OptionStepList": "./src/components/molecules/OptionStepList",
  "./Panel": "./src/components/molecules/Panel",
  "./PanelCollapsible": "./src/components/molecules/PanelCollapsible",
  "./PanelWithList": "./src/components/molecules/PanelWithList",
  "./Popover": "./src/components/molecules/Popover",
  "./Popup": "./src/components/molecules/Popup",
  "./ScalableImage": "./src/components/molecules/ScalableImage",
  "./SelectorsGroup": "./src/components/molecules/SelectorsGroup",
  "./SensorIndicator": "./src/components/molecules/SensorIndicator",
  "./SpinnerContainer": "./src/components/molecules/SpinnerContainer",
  "./StatusWithDeadline": "./src/components/molecules/StatusWithDeadline",
  "./Table": "./src/components/molecules/Table",
  "./Tabs": "./src/components/molecules/Tabs",
  "./TemplateReportButton": "./src/components/molecules/TemplateReportButton",
  "./TreeView": "./src/components/molecules/TreeView",
  "./devices": "./src/components/molecules/devices",
  "./emergency": "./src/components/molecules/emergency",
  "./incidents": "./src/components/molecules/incidents",
  "./scenaries": "./src/components/molecules/scenaries",
  "./signals": "./src/components/molecules/signals",
  "./AsideMenuMinifiable": "./src/components/organisms/AsideMenuMinifiable",
  "./AudioPlayer": "./src/components/organisms/AudioPlayer",
  "./ChangeLocationModal": "./src/components/organisms/ChangeLocationModal",
  "./charts": "./src/components/organisms/Charts",
  "./CollapsedDrawerPanel": "./src/components/organisms/CollapsedDrawerPanel",
  "./ContactsListCheckboxTree":
    "./src/components/organisms/ContactsListCheckboxTree",
  "./Drawer": "./src/components/organisms/Drawer",
  "./ErrorBoundary": "./src/components/organisms/ErrorBoundary",
  "./FilterButton": "./src/components/organisms/FilterButton",
  "./form": "./src/components/organisms/Form",
  "./FrameContainer": "./src/components/organisms/FrameContainer",
  "./LayersTreeView": "./src/components/organisms/LayersTreeView",
  "./NavMenu": "./src/components/organisms/NavMenu",
  "./NotificationProcessGroupListItem":
    "./src/components/organisms/NotificationProcessGroupListItem",
  "./NotificationsDrawer": "./src/components/organisms/NotificationsDrawer",
  "./Pagination": "./src/components/organisms/Pagination",
  "./SaveChangesModal": "./src/components/organisms/SaveChangesModal",
  "./SelectedFiltersBlock": "./src/components/organisms/SelectedFiltersBlock",
  "./SelectNotificationDestinationsList":
    "./src/components/organisms/SelectNotificationDestinationsList",
  "./SortableDragNDropList": "./src/components/organisms/SortableDragNDropList",
  "./SortFilter": "./src/components/organisms/SortFilter",
  "./TableSortHeader": "./src/components/organisms/TableSortHeader",
  "./Toaster": "./src/components/organisms/Toaster",
  "./Tooltip": "./src/components/organisms/Tooltip",
  "./videoPlayers": "./src/components/organisms/videoPlayers",
  "./WeatherForecastWidget": "./src/components/organisms/WeatherForecastWidget",
  "./WeatherWidget": "./src/components/organisms/WeatherWidget",
  "./WSPushToaster": "./src/components/organisms/WSPushToaster",
  "./templates": "./src/components/templates",
  "./contexts": "./src/contexts",
  "./config": "./src/config",
  "./constants": "./src/constants",
  "./hooks": "./src/hooks",
  "./images": "./src/images",
  "./store": "./src/store",
  "./utils": "./src/utils",
  "./styles": "./src/styles",
  "./router": "./src/router/saga",
  "./common": "./src/types/common",
};
